title: eviLittle
description: How much evil must we do to do good? 

url: https://evilittle.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: evilittle
   twitter: evilittle
   facebook: evilittle
   email: rexlee8776@gmail.com

google_analytics: "UA-72419052-1"
